name: publish

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: dotnet tool restore

    - name: Build the project
      run: |
        dotnet fsi build.fsx -p bundle

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist